nextcloud:
  metrics:
    enabled: true
  trustedDomains:
    - nextcloud.ikanago.dev
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    existingSecret:
      enabled: true
      secretName: nextcloud-postgresql-creds
      usernameKey: username
      passwordKey: user-password
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          existingSecret: nextcloud-postgresql-creds
          secretKeys:
            adminPasswordKey: admin-password
            userPasswordKey: user-password
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
        labels:
          recurring-job.longhorn.io/snapshot: enabled
