nextcloud:
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
  persistence:
    nextcloudData:
      enabled: true
      size: 20Gi
      storageClass: longhorn
      annotations:
        recurring-job.longhorn.io/snapshot: enabled
  metrics:
    enabled: true
  postgresql:
    global:
      postgresql:
        auth:
          existingSecret: nextcloud-postgresql-creds
          secretKeys:
            adminPasswordKey: admin-password
            userPasswordKey: user-password
