nextcloud:
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
  persistence:
    enabled: true
    storageClass: longhorn
    size: 4Gi
    nextcloudData:
      enabled: true
      size: 4Gi
      storageClass: longhorn
  metrics:
    enabled: true
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          existingSecret: nextcloud-postgresql-creds
          secretKeys:
            adminPasswordKey: admin-password
            userPasswordKey: user-password
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
        labels:
          recurring-job.longhorn.io/snapshot: enabled
