cloudflare-tunnel:
  cloudflare:
    # The name of the tunnel this instance will serve
    tunnelName: "vega-k3s"
    # If defined, no secret is created for the credentials, and instead, the secret referenced is used
    secretName: "cloudflare-tunnel-credentials"
    # Define ingress rules for the tunnel. See
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress
    ingress:
      - hostname: grafana.ikanago.dev
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80

  image:
    tag: "2024.6.0"
