longhorn:
  persistence:
    defaultClassReplicaCount: 1

  defaultSettings:
    snapshotMaxCount: 50

  longhornUI:
    replicas: 1

  metrics:
    serviceMonitor:
      enabled: true

  preUpgradeChecker:
    jobEnabled: false
