apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: switchbot-ble-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: switchbot-ble-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: switchbot-ble-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: switchbot-ble-exporter
    spec:
      hostNetwork: true
      containers:
        - name: switchbot-ble-exporter
          image: ghcr.io/ikanago/switchbot_ble_exporter:latest@sha256:88e77b83bc6cbae8d965e985c9af7a8943d8a0302626d24910f918d8658d862c
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: RUST_LOG
              value: "debug"
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 60
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
