apiVersion: apps/v1
kind: Deployment
metadata:
  name: switchbot-ble-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: switchbot-ble-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: switchbot-ble-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: switchbot-ble-exporter
    spec:
      containers:
        - name: switchbot-ble-exporter
          image: ghcr.io/ikanago/switchbot_ble_exporter:latest@sha256:801a44964512a11df9a16826654b6ebc56dcff93ab3b6b49cda3c9a09e785ae7
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: RUST_LOG
              value: "info"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      hostNetwork: true
