apiVersion: apps/v1
kind: Deployment
metadata:
  name: switchbot-ble-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: switchbot-ble-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: switchbot-ble-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: switchbot-ble-exporter
    spec:
      containers:
        - name: switchbot-ble-exporter
          image: ghcr.io/ikanago/switchbot_ble_exporter:latest@sha256:2140ac0030d9f71c2ea8102cce627947b5a6681c2ebc128aa82c0719186ca8bf
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: RUST_LOG
              value: "info"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      hostNetwork: true
