apiVersion: v1
kind: Pod
metadata:
  name: switchbot-ble-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: switchbot-ble-exporter
spec:
  containers:
    - name: switchbot-ble-exporter
      image: ghcr.io/ikanago/switchbot_ble_exporter:latest@sha256:9832f8a1d78b00441b603c63c524b2fd82a553df608c54cb995ee8aa23569c08
      ports:
        - containerPort: 8080
      env:
        - name: PORT
          value: "8080"
        - name: RUST_LOG
          value: "info"
      resources:
        limits:
          cpu: 100m
          memory: 32Mi
      livenessProbe:
        httpGet:
          path: /
          port: 8080
          initialDelaySeconds: 5
          periodSeconds: 300
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  hostNetwork: true
