apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: switchbot-ble-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: switchbot-ble-exporter
    app.kubernetes.io/component: exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: switchbot-ble-exporter
  endpoints:
    - scheme: http
      path: /metrics
      targetPort: 8080
      interval: 1m
  namespaceSelector:
    any: true
