apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: switchbot-ble-exporter
  namespace: monitoring
  labels:
    app: switchbot-ble-exporter
spec:
  selector:
    matchLabels:
      app: switchbot-ble-exporter
  endpoints:
    - scheme: http
      path: /metrics
      targetPort: 8080
      interval: 1m
  namaspaceSelector:
    any: true
