apiVersion: v1
kind: Service
metadata:
  name: switchbot-ble-exporter
  namespace: monitoring
  labels:
    app: switchbot-ble-exporter
spec:
  selector:
    app: switchbot-ble-exporter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
